language: python
python:
- 3.8
- 3.7
- 3.6
install: make
script:
- make test
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: JH+jZurJRm5VL7p/wqexKU01bvvTqK40mZoRzrbAfrlAzVdVf/sNFvFgg2pu/0pXg6zRw5ywsr4kvBsaef6H8f8UQFCsRo3qdRC84mZzg5D+6rM9PG4XmlKxlAKvGLw6tBPpO/LLpXEuNybLQ0GkqwpbXUDcj4GMa9B+ug7YLXQoFdpCqT20U0Sdo+yv7VN6rHlOMzwQuHKkbsbZe0H+xGFE4O3cxIlqqqn/eFUp4wU8L9Y3nua/N1uRsGwo6CTfpNFa9y7RHddhSjj2wqOG46+EkoIIt6wvVCqKoxrnQ3CevZKPkhdNyG8p3sMFRuJaN2iRLj8gAODJ8H6myTCgHnsbgXRzNPA0MxWsmBkv0aF2Yz7Qv+qbS2sfYX6Nu0AC5xxgl8U22fGTthP3bHR1HS0ZoE91pMgMFZrxqsx5LxHQ1mOINDVc9ByUS91DAfPw7GBGxeIawo8LWEaONO7zvbzChg8K6b8B6fo/1DZMyAUMV6dkdH/UusiMwqtDhTFTAY0W7PQXk7nJkiCNNYBc3jO1eLEVg5DEQVQy0JTSMS43o+kMiKlIbqKsVrWr4AotuLEptasATxPXYadvlPw23E4AjHMEwNnQy+x/ZWwhjflQWYXtkXb1M+dIugkLnkYNdkXjIwSzmil5Py6HK49HG2VOCR0925Mx/Np+KnZGnCo=
  on:
    tags: true
    repo: johanthoren/check_sl_delay
    python: 3.8
env:
  global:
  - secure: YnzehtQt3KdLIef9Aygq4tT/JEadEcUCq6wY/kYVzBvWtezYrfvRbK3kwL4w0olpcnJokcOYPG3Cwrk06H8K9zgu6IvEsz91tcF5MyQyvAnxSyDBvzgZxgOul+ir9r7ZRKN0MebJKeEqQFW9sEy0F1rbXIq63I461v3z5/VNnfjUg7x3cLIdJO7e3vC9Du1DyEPenn5ONYxbnEoNpVH3yuNOccry9rzpAoYjJuDR20XfxRwAvGdXDzyRdnkb8UH1YocDh8MZrXzRGsh4GcGSHeYV/kxGdAVnd0rF/1LmAZDmKKElDKf2LrvfaCRiG6d5ugDwsl22Vq66zFstbaXd9B8XHttLaoYtDoNUNSv7U4DLQvRgNXPdoLTplrJ3GVa668oK8VMbZX/nJ7T8UMrayQ7H3kWNu8LwJPlMV8t5EZ4B/4Jz4Cc1UmCc21oNV9HqbMfdOPe1iXuLxFGPIUWx0h2TjpP1QO1OUs8jQrxX3lqS8SO0vn16iwyUt94i6E4EahuJ3ilpk9pc7CBlj4yOYncwmh5xTq65rv6ntL9ooW+upCk4xECNeWVCvGe322oq+hjyy+vzHOl9KdnKComYxs7VGLgh5dbh7jp8hvaDS7n2DSY/INQdNwMCoqUzVbx394JFuIcNBHRs4hM2wmAUS8pDAGXD4nSPFsEqTSDhGuo=
  - secure: SCFO6MgjuKc+UpshrejLYfQxRDDlqgB1aOLUPpMtSnWzksJBnVJrLZpZLoL5NKkAHyYuGYOjvmVpkdDXnSRo28jXk6BxmofoaQhp01y/1Obqn24+clI4fhO9DUIPR+djlr4rJRKHWnyuKfnFxU4rWBXd5wWzzr/WjMqcVoVzbOGzUIRuEXnY4wgZRLzW3ZOM2pLWkVhQfRWAV5CyVHs9zikcg8nEcdHw2Mk47T5xTm949cIfryNbYQsxBg1hTe6+POLf8T58et8oJQn2QzWEJ/NUJ6WXIHDaxJOFCHm/reXQ8XpnQk63xIwPo+NPHXZxOZjemGC90REeUx6Hyy7DQXVPHVWnP+chJ1aajNuHJMXwxOMQzDQiHBCLTRvmBv3TmnXt7dYjVXeEbFkg27vB/oHVO7lzgJHL/EVsqLv0BqcndFe24jcL/9rX5jSTy3wM/F8ilNMIvbH6HC4j2fa0OiK1tYg1o6JYF67B6GMj5GnPR+METFhdmRIC9BNDugIK03MtJqK+kxkwqB/Nk1ljteTM2qX7ChJ7Ixi1LQdz7UocSsAmC3Yo6RXoEQ5QzHUDcNjvQDL+JhfUosIp6f1fJkUouEmvd0EMy2m/V6vgNvCn3NMMWv27vHWjUDfg8EMW4GSA5iVkG/1JXgVxkdWJy6WzDeArxrGpjzsKZKUCZeE=
