language: python
python:
- 3.8
- 3.7
- 3.6
install: make
script:
- make test
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: JH+jZurJRm5VL7p/wqexKU01bvvTqK40mZoRzrbAfrlAzVdVf/sNFvFgg2pu/0pXg6zRw5ywsr4kvBsaef6H8f8UQFCsRo3qdRC84mZzg5D+6rM9PG4XmlKxlAKvGLw6tBPpO/LLpXEuNybLQ0GkqwpbXUDcj4GMa9B+ug7YLXQoFdpCqT20U0Sdo+yv7VN6rHlOMzwQuHKkbsbZe0H+xGFE4O3cxIlqqqn/eFUp4wU8L9Y3nua/N1uRsGwo6CTfpNFa9y7RHddhSjj2wqOG46+EkoIIt6wvVCqKoxrnQ3CevZKPkhdNyG8p3sMFRuJaN2iRLj8gAODJ8H6myTCgHnsbgXRzNPA0MxWsmBkv0aF2Yz7Qv+qbS2sfYX6Nu0AC5xxgl8U22fGTthP3bHR1HS0ZoE91pMgMFZrxqsx5LxHQ1mOINDVc9ByUS91DAfPw7GBGxeIawo8LWEaONO7zvbzChg8K6b8B6fo/1DZMyAUMV6dkdH/UusiMwqtDhTFTAY0W7PQXk7nJkiCNNYBc3jO1eLEVg5DEQVQy0JTSMS43o+kMiKlIbqKsVrWr4AotuLEptasATxPXYadvlPw23E4AjHMEwNnQy+x/ZWwhjflQWYXtkXb1M+dIugkLnkYNdkXjIwSzmil5Py6HK49HG2VOCR0925Mx/Np+KnZGnCo=
  on:
    tags: true
    repo: johanthoren/check_sl_delay
    python: 3.8
